version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=marouane
      - MONGO_INITDB_ROOT_PASSWORD=password

  app:
    depends_on:
      - mongodb
    build: .
    environment:
      - DB_URL=mongodb://marouane:password@mongodb/badumts?authSource=admin
    ports:
      - "8080:8080"